## *Pandas*

In [ ]:
#installation
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#standard imports
import pandas as pd
import numpy as np

In [ ]:
#version
print(pd.__version__)

2.2.2

In [ ]:
print(np.__version__)

2.0.2

In [ ]:
#series  creating using list
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#indexing customi
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#dictionary
students={
    "name":"teja",
    "branch":"aiml"
}
he=pd.Series(students)
print(he)

name      teja
branch    aiml
dtype: object

In [ ]:
#operations
j=pd.Series([10,20,30,40,50])
print(j)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
j+2

0    12
1    22
2    32
3    42
4    52
dtype: int64

In [ ]:
j*2

0     20
1     40
2     60
3     80
4    100
dtype: int64

In [ ]:
j-2

0     8
1    18
2    28
3    38
4    48
dtype: int64

In [ ]:
j/2

0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64

In [ ]:
#statistics
j.mean()

np.float64(30.0)

In [ ]:
j.min()

10

In [ ]:
j.max()

50

In [ ]:
j.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [ ]:
#bolean indexing
j[j>30]

3    40
4    50
dtype: int64

In [ ]:
#vectorize dstring operations
n=pd.Series(['vamsi','harsha','vishnu'])
n.str.lower()

0     vamsi
1    harsha
2    vishnu
dtype: object

In [ ]:
n.str.upper()

0     VAMSI
1    HARSHA
2    VISHNU
dtype: object

In [ ]:
n.str.len()

0    5
1    6
2    6
dtype: int64

In [ ]:
n.str.startswith("v")

0     True
1    False
2     True
dtype: bool

# Pandas **DataFrames**

In [ ]:
#crete data frame
students={
    "name":['vamsi','teja','satti','visu','manoj'],
    "branch":['aiml','aiml','aiml','aiml','aiml']
}
d=pd.DataFrame(students)
print(d)

    name branch
0  vamsi   aiml
1   teja   aiml
2  satti   aiml
3   visu   aiml
4  manoj   aiml

In [ ]:
#from list of dicts
std=[
    {"name":"vamsi","branch":"aiml"},
    {"name":"teja","branch":"aiml"},
    {"name":"satti","branch":"aiml"},
    {"name":"visu","branch":"aiml"},
    {"name":"manoj","branch":"aiml"},
]
d=pd.DataFrame(std)
print(d)

    name branch
0  vamsi   aiml
1   teja   aiml
2  satti   aiml
3   visu   aiml
4  manoj   aiml

In [ ]:
#from numpy array
arr=np.random.rand(3,4)
d=pd.DataFrame(arr,columns=['a','b','c','d'],index=['x','y','z'])
print(d)

          a         b         c         d
x  0.357397  0.844114  0.881086  0.692363
y  0.003602  0.156025  0.040615  0.674270
z  0.532367  0.582206  0.395432  0.158714

In [ ]:
#exploring data frames
data={
    "name":['manoj','visu','teja','satti'],
    "Age":[23,25,22,28],
    "score":[88,75,45,38],
    "grade":['A','B','C','D']
}
df=pd.DataFrame(data)
print(df)

    name  Age  score grade
0  manoj   23     88     A
1   visu   25     75     B
2   teja   22     45     C
3  satti   28     38     D

In [ ]:
df.head(3)

    name  Age  score grade
0  manoj   23     88     A
1   visu   25     75     B
2   teja   22     45     C

In [ ]:
df.tail(2)

    name  Age  score grade
2   teja   22     45     C
3  satti   28     38     D

In [ ]:
df.shape

(4, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   Age     4 non-null      int64
 2   score   4 non-null      int64
 3   grade   4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

             Age      score
count   4.000000   4.000000
mean   24.500000  61.500000
std     2.645751  23.867691
min    22.000000  38.000000
25%    22.750000  43.250000
50%    24.000000  60.000000
75%    25.750000  78.250000
max    28.000000  88.000000

In [ ]:
df.columns

Index(['name', 'Age', 'score', 'grade'], dtype='object')

In [ ]:
df.isnull()

    name    Age  score  grade
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
#selecting columns
#single column
df['name']

0    manoj
1     visu
2     teja
3    satti
Name: name, dtype: object

In [ ]:
#multiple columns
df[['name','grade']]

    name grade
0  manoj     A
1   visu     B
2   teja     C
3  satti     D

In [ ]:
#selecting rows
#loc
df.loc[0]

name     manoj
Age         23
score       88
grade        A
Name: 0, dtype: object

In [ ]:
df.loc[0:2]

    name  Age  score grade
0  manoj   23     88     A
1   visu   25     75     B
2   teja   22     45     C

In [ ]:
df.loc[0:2,"name":"score"]

    name  Age  score
0  manoj   23     88
1   visu   25     75
2   teja   22     45

In [ ]:
df.iloc[0]

name     manoj
Age         23
score       88
grade        A
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

    name  Age  score grade
0  manoj   23     88     A
1   visu   25     75     B

In [ ]:
df.iloc[0:2 ,0:2]

    name  Age
0  manoj   23
1   visu   25

In [ ]:
df.iloc[-1]

name     satti
Age         28
score       38
grade        D
Name: 3, dtype: object

In [ ]:
#single value
df.loc[0,'name']
df.iloc[0,0]

'manoj'

In [ ]:
df[(df['score']>80) & (df['grade'] == 'A')]

    name  Age  score grade
0  manoj   23     88     A

In [ ]:
#query
df.query('score > 80 and Age <25')

    name  Age  score grade
0  manoj   23     88     A

In [ ]:
df.query('grade =="A"')

    name  Age  score grade
0  manoj   23     88     A

In [ ]:
df[df['name'].isin(['manoj','vishnu'])]

    name  Age  score grade
0  manoj   23     88     A

In [ ]:
#add a new column
df['example']=["a","b","c","d"]

In [ ]:
df['grade']=df['score']>=55

In [ ]:
print(df)

    name  Age  score  grade example
0  manoj   23     88   True       a
1   visu   25     75   True       b
2   teja   22     45  False       c
3  satti   28     38  False       d

In [ ]:
#modify existing column
df['score']=df['score']+5

In [ ]:
print(df)

    name  Age  score grade example  grade_letter
0  manoj   23     93     A       a            93
1   visu   25     80     B       b            80
2   teja   22     50     C       c            50
3  satti   28     43     C       d            43

In [ ]:
def grade(score):
  if(score>90):
    return'A'
  elif(score>=80):
    return 'B'
  else:
      return 'C'

#apply function
df['grade_letter']=df['score'].apply(grade)

print(df)

    name  Age  score grade example  grade_letter
0  manoj   23     93     A       a            93
1   visu   25     80     B       b            80
2   teja   22     50     C       c            50
3  satti   28     43     C       d            43

In [ ]:
result={
    True:"pass",
    False:"fail"
}
pas={'A':90,'B':80,'D':60}

df['pass']=df['grade'].map(pas)
df['result']=df['grade'].map(result)
print(df)

    name  Age  score grade example  grade_letter  pass result
0  manoj   23     93     A       a            93  90.0    NaN
1   visu   25     80     B       b            80  80.0    NaN
2   teja   22     50     C       c            50   NaN    NaN
3  satti   28     43     C       d            43   NaN    NaN

In [ ]:
df.drop('pass',axis=1,inplace=True)

In [ ]:
print(df)

    name  Age  score grade example result
0  manoj   23     93     A       a    NaN
1   visu   25     80     B       b    NaN
2   teja   22     50     C       c    NaN
3  satti   28     43     C       d    NaN

In [ ]:
df.rename(columns={'score' :'marks','name' :'students'}, inplace=True)

In [ ]:
print(df)

  students  Age  marks grade example result
0    manoj   23     93     A       a    NaN
1     visu   25     80     B       b    NaN
2     teja   22     50     C       c    NaN
3    satti   28     43     C       d    NaN

In [ ]:
df.replace('A',np.nan,inplace=True)

In [ ]:
print(df)

  students  Age  marks grade example result
0    manoj   23     93   NaN       a    NaN
1     visu   25     80     B       b    NaN
2     teja   22     50     C       c    NaN
3    satti   28     43     C       d    NaN

In [ ]:
#sort by single column
df.sort_values('marks',ascending=False)

  students  Age  marks grade example result
0    manoj   23     93   NaN       a    NaN
1     visu   25     80     B       b    NaN
2     teja   22     50     C       c    NaN
3    satti   28     43     C       d    NaN

In [ ]:
df.sort_values('marks',ascending=True)

  students  Age  marks grade example result
3    satti   28     43     C       d    NaN
2     teja   22     50     C       c    NaN
1     visu   25     80     B       b    NaN
0    manoj   23     93   NaN       a    NaN

In [ ]:
df.sort_values(['Age','marks'],ascending=[True,False])

  students  Age  marks grade example result
2     teja   22     50     C       c    NaN
0    manoj   23     93   NaN       a    NaN
1     visu   25     80     B       b    NaN
3    satti   28     43     C       d    NaN

In [ ]:
#sort by index
df.sort_index(ascending=False)

  students  Age  marks grade example result
3    satti   28     43     C       d    NaN
2     teja   22     50     C       c    NaN
1     visu   25     80     B       b    NaN
0    manoj   23     93   NaN       a    NaN

In [ ]:
#get top N rows
df.nlargest(4,'marks')

  students  Age  marks grade example result
0    manoj   23     93   NaN       a    NaN
1     visu   25     80     B       b    NaN
2     teja   22     50     C       c    NaN
3    satti   28     43     C       d    NaN

In [ ]:
df.nsmallest(3,'Age')

  students  Age  marks grade example result
2     teja   22     50     C       c    NaN
0    manoj   23     93   NaN       a    NaN
1     visu   25     80     B       b    NaN

In [ ]:
o={
    'Department':['IT','HR','IT','HR','IT','HR'],
    'Employee':['A','B','C','D','E','F'],
    'Salary':[10000,20000,30000,40000,50000,60000]
}
df=pd.DataFrame(o)
print(df)

  Department Employee  Salary
0         IT        A   10000
1         HR        B   20000
2         IT        C   30000
3         HR        D   40000
4         IT        E   50000
5         HR        F   60000

In [ ]:
df.groupby('Department')['Salary'].min()

Department
HR    20000
IT    10000
Name: Salary, dtype: int64

In [ ]:
df.groupby('Department')['Salary'].max()

Department
HR    60000
IT    50000
Name: Salary, dtype: int64

In [ ]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'dept_id': [10, 20, 10, 30]
})

departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['Engineering', 'HR']
})

In [ ]:
#inner join
pd.merge(employees,departments,on='dept_id',how='inner')

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering

In [ ]:
#inner join
pd.merge(employees,departments,on='dept_id',how='outer')

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       3  Charlie       10  Engineering
2       2      Bob       20           HR
3       4    Diana       30          NaN

In [ ]:

pd.merge(employees,departments,on='dept_id',how='left')

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering
3       4    Diana       30          NaN

In [ ]:

pd.merge(employees,departments,on='dept_id',how='right')

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       3  Charlie       10  Engineering
2       2      Bob       20           HR